### ISSUE TITLE
Verify file downloaded

### ISSUE THREAD

**Issue by GaryJones** [brightnucleus/geolite2-country#2]
Before saving to the final file, the package should download to a temporary location, and check the [`md5_file()`](http://php.net/manual/en/function.md5-file.php) of the contents. If they match the provided md5 from MaxMind, copy the file to the desired location. Otherwise, inform the user. Delete the temporary file at the end.

**Comment by schlessera** [comment]
Yes, good point, will roll this in for the next iteration.

**Comment by slaFFik** [comment]
That would be a very nice addition.
